[build]
  functions = "functions"
  command = "netlify-lambda install && npm install axios dotenv openai &&mkdir ./public"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200